"""add user name and itinerary json

Revision ID: bdbd41787068
Revises: 93f86fd5e218
Create Date: 2026-03-18 15:25:13.246849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bdbd41787068'
down_revision: Union[str, Sequence[str], None] = '93f86fd5e218'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trip_members',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('trip_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('invited_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trip_id', 'user_id', name='uq_trip_member_trip_user')
    )
    op.create_index(op.f('ix_trip_members_trip_id'), 'trip_members', ['trip_id'], unique=False)
    op.create_index(op.f('ix_trip_members_user_id'), 'trip_members', ['user_id'], unique=False)
    op.add_column('trips', sa.Column('itinerary_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('trips', 'destination_iata',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('trips', 'end_date')
    op.drop_column('trips', 'start_date')
    op.add_column('users', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    op.add_column('trips', sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('trips', sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True))
    op.alter_column('trips', 'destination_iata',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('trips', 'itinerary_json')
    op.drop_index(op.f('ix_trip_members_user_id'), table_name='trip_members')
    op.drop_index(op.f('ix_trip_members_trip_id'), table_name='trip_members')
    op.drop_table('trip_members')
    # ### end Alembic commands ###
